services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${TAG:-latest}
    image: makxies24/edutrack:${TAG:-latest}
    container_name: edutrack-container
    ports:
      - "8082:443"       # HTTPS traffic
      # - "8080:80"     # Optional: redirect HTTP to HTTPS
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - APP_KEY=${APP_KEY}
    volumes:
      - ${PWD}/.env.docker:/var/www/html/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  db:
    image: mariadb:10.5
    container_name: mariadb-edutrack
    environment:
      - MYSQL_DATABASE=edutrack
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  app_data:
    driver: local







# # v1.0
# # version: '3.8' verioning do not required on the latest docker compose

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         APP_VERSION: ${BUILD_NUMBER}
#     image: makxies24/edutrack:${BUILD_NUMBER}
#     container_name: edutrack-container
#     ports:
#       - "80:80"
#     networks:
#       - app-network
#     depends_on:
#       - db
#     environment:
#       - APP_KEY=${APP_KEY}
#     #   - APP_ENV=local
#     #   - APP_DEBUG=true
#     volumes:
#       - ./.env-db:/var/www/html/.env  # Bind mount `.env-db` to `.env` in the container
#     healthcheck:
#       test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     restart: always

#   db:
#     image: mariadb:10.5
#     container_name: mariadb
#     environment:
#       - MYSQL_DATABASE=edutrack
#       - MYSQL_USER=root
#       - MYSQL_ALLOW_EMPTY_PASSWORD="yes"  # No password for root user
#     ports:
#       - "3306:3306"  # Expose MariaDB port
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - app-network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#     restart: always

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db_data:
#     driver: local
